### ISSUE TITLE
Hall of Fame displays before Final Round Winner

### ISSUE THREAD

**Issue by danielbergamin** [ckiely91/acrofever#18]
Perhaps this is deliberate, but seems a little bit strange

**Comment by ckiely91** [comment]
Was deliberate as the last round results is actually on the same page as the hall of fame voting. Can see what you mean though. Bit hard to lay out properly, as I didn't want another timer/button-press before people vote for hall of fame.

**Comment by danielbergamin** [comment]
Ahh fair call! I did notice it last night, thought you had made a change haha. Good to know, I think maybe close this for now then.
