### ISSUE TITLE
Support Facebook/Twitter/Google social login

### ISSUE THREAD

**Issue by danielbergamin** [ckiely91/acrofever#5]
Allow multiple sources of authentication.

Possibly there is a meteor package that will make this easy, investigate that avenue before cutting any custom code.

**Comment by danielbergamin** [comment]
Along the same lines, we could look at adding some social integration - at a most basic level, set up accounts and Like/Tweet etc; getting more advanced we could have a bot that auto-posts hall of fame entries etc.

**Comment by ckiely91** [comment]
If there's enough demand, maybe we could also allow people to play by just inputting a temporary username. This would have limited features though, such as not eligible for hall of fame, cannot create lobbies, etc. Need to investigate repercussions further. 

For external authentication like FB, Google, Twitter, pretty sure there will be packages available for it.

**Comment by ckiely91** [comment]
Facebook, Google and Twitter are now implemented.
