### ISSUE TITLE
End game when a user reaches certain number of points

### ISSUE THREAD

**Issue by ckiely91** [ckiely91/acrofever#9]
This should set an ultimate winner at a defined point limit. This will be an option for game creators upon the creation of a game too. 

Another possibility is to play a "final" round when a player hits the winning number of points. The first and second scorers (and anyone who tied for second) will play a final challenge round where everyone else votes for their favourite. The winner of that round then wins the whole game. 
May be unfair if there is a big disparity between first and second place though.

**Comment by danielbergamin** [comment]
Also could have the option to do it based on a round limit. I think the key
is to make sure the defaults allow enough time for a healthy competition,
but declaring a winner and resetting often enough to not let someone sit
tragically behind for a long time.

**Comment by ckiely91** [comment]
This is now implemented with a point limit. Round limit can come later.

**Comment by ckiely91** [comment]
I'll close this for now. I think a point limit is the way to go for the time being. Can open a new issue if a round limit becomes something people want.
